# Generated by Django 3.2.24 on 2024-03-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyleader', models.CharField(max_length=100)),
                ('partyname', models.CharField(max_length=100)),
                ('voter', models.CharField(max_length=100)),
            ],
        ),
    ]
